modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/IAmREGE/FlPoSn/issues"

[[mods]]
modId="flposn"
version="0.0.1"
displayName="FlPoSn"
description="Make Powder Snow flowable"
displayURL="https://github.com/IAmREGE/FlPoSn"
logoFile="icon.png"
authors="RheniumGermanide"

[[mixins]]
config="flposn.mixins.json"
